# Base image
FROM node:18-alpine AS development

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY  package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . /app

# Expose the port for development server
EXPOSE 3001

# Start the development server
CMD ["npm", "run", "dev"]