# Base image for building the app
FROM node:18-alpine AS build
# Set working directory
WORKDIR /app
# Copy package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy the entire project
COPY . ./
# Build the application
RUN npm run build


# Production image
FROM nginx:1-alpine
# Copy build files from the build stage
COPY --from=build /app/dist /usr/share/nginx/html
# Expose the port
EXPOSE 80
# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
